### ISSUE TITLE
Broken Pry

### ISSUE THREAD

**Issue by jhn** [rking/pry-plus#1]
Just installed your gem and now I get this error every time I try to start pry:

`/Users/jhn/.rvm/gems/ruby-1.9.3-p194@rails327/bin/ruby_noexec_wrapper:14: stack level too deep (SystemStackError)`

I'm using [this custom .pryrc](https://github.com/skwp/dotfiles).

**Comment by rking** [comment]
Hi Johan!

Thanks for the report.

Let me find my stethoscope… ahh yes, there it is.

What version of `pry-exception_explorer` are you running?  If it's >0.1.9, try `gem uninstall pry-exception_explorer` for all the 0.2.\* versions you have.

If that doesn't work, please paste me the output of `gem list pry`

**Comment by jhn** [comment]
I'm running 0.1.9. When I run `gem list pry`, I get this:

`pry (0.9.10)
pry-debugger (0.2.0)
pry-doc (0.4.4)
pry-exception_explorer (0.1.9)
pry-nav (0.2.2)
pry-plus (0.1)
pry-rescue (0.13)
pry-stack_explorer (0.4.7)`

Do you want me to uninstall all gems that start with 0.2.\* (pry-debugger and pry-nav) and reinstall them?

**Comment by rking** [comment]
Oh, the problem is definitely pry-nav. Remove it and you're good.

**Comment by jhn** [comment]
Aaaaaaaaand Pry is back! Thanks, doc!
